// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog/internal/ent/blog"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlogCreate is the builder for creating a Blog entity.
type BlogCreate struct {
	config
	mutation *BlogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (bc *BlogCreate) SetCreatedAt(i int64) *BlogCreate {
	bc.mutation.SetCreatedAt(i)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BlogCreate) SetNillableCreatedAt(i *int64) *BlogCreate {
	if i != nil {
		bc.SetCreatedAt(*i)
	}
	return bc
}

// SetCreatedBy sets the "created_by" field.
func (bc *BlogCreate) SetCreatedBy(s string) *BlogCreate {
	bc.mutation.SetCreatedBy(s)
	return bc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (bc *BlogCreate) SetNillableCreatedBy(s *string) *BlogCreate {
	if s != nil {
		bc.SetCreatedBy(*s)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BlogCreate) SetUpdatedAt(i int64) *BlogCreate {
	bc.mutation.SetUpdatedAt(i)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BlogCreate) SetNillableUpdatedAt(i *int64) *BlogCreate {
	if i != nil {
		bc.SetUpdatedAt(*i)
	}
	return bc
}

// SetUpdatedBy sets the "updated_by" field.
func (bc *BlogCreate) SetUpdatedBy(s string) *BlogCreate {
	bc.mutation.SetUpdatedBy(s)
	return bc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (bc *BlogCreate) SetNillableUpdatedBy(s *string) *BlogCreate {
	if s != nil {
		bc.SetUpdatedBy(*s)
	}
	return bc
}

// SetIsDeleted sets the "is_deleted" field.
func (bc *BlogCreate) SetIsDeleted(u uint8) *BlogCreate {
	bc.mutation.SetIsDeleted(u)
	return bc
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (bc *BlogCreate) SetNillableIsDeleted(u *uint8) *BlogCreate {
	if u != nil {
		bc.SetIsDeleted(*u)
	}
	return bc
}

// SetDeletedAt sets the "deleted_at" field.
func (bc *BlogCreate) SetDeletedAt(i int64) *BlogCreate {
	bc.mutation.SetDeletedAt(i)
	return bc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (bc *BlogCreate) SetNillableDeletedAt(i *int64) *BlogCreate {
	if i != nil {
		bc.SetDeletedAt(*i)
	}
	return bc
}

// SetDeletedBy sets the "deleted_by" field.
func (bc *BlogCreate) SetDeletedBy(s string) *BlogCreate {
	bc.mutation.SetDeletedBy(s)
	return bc
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (bc *BlogCreate) SetNillableDeletedBy(s *string) *BlogCreate {
	if s != nil {
		bc.SetDeletedBy(*s)
	}
	return bc
}

// SetAccountID sets the "account_id" field.
func (bc *BlogCreate) SetAccountID(i int32) *BlogCreate {
	bc.mutation.SetAccountID(i)
	return bc
}

// SetTitle sets the "title" field.
func (bc *BlogCreate) SetTitle(s string) *BlogCreate {
	bc.mutation.SetTitle(s)
	return bc
}

// SetDescription sets the "description" field.
func (bc *BlogCreate) SetDescription(s string) *BlogCreate {
	bc.mutation.SetDescription(s)
	return bc
}

// SetIsHidden sets the "is_hidden" field.
func (bc *BlogCreate) SetIsHidden(i int8) *BlogCreate {
	bc.mutation.SetIsHidden(i)
	return bc
}

// SetNillableIsHidden sets the "is_hidden" field if the given value is not nil.
func (bc *BlogCreate) SetNillableIsHidden(i *int8) *BlogCreate {
	if i != nil {
		bc.SetIsHidden(*i)
	}
	return bc
}

// SetTags sets the "tags" field.
func (bc *BlogCreate) SetTags(s []string) *BlogCreate {
	bc.mutation.SetTags(s)
	return bc
}

// SetCover sets the "cover" field.
func (bc *BlogCreate) SetCover(s string) *BlogCreate {
	bc.mutation.SetCover(s)
	return bc
}

// SetContent sets the "content" field.
func (bc *BlogCreate) SetContent(s string) *BlogCreate {
	bc.mutation.SetContent(s)
	return bc
}

// SetID sets the "id" field.
func (bc *BlogCreate) SetID(i int32) *BlogCreate {
	bc.mutation.SetID(i)
	return bc
}

// Mutation returns the BlogMutation object of the builder.
func (bc *BlogCreate) Mutation() *BlogMutation {
	return bc.mutation
}

// Save creates the Blog in the database.
func (bc *BlogCreate) Save(ctx context.Context) (*Blog, error) {
	if err := bc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BlogCreate) SaveX(ctx context.Context) *Blog {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BlogCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BlogCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BlogCreate) defaults() error {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := blog.DefaultCreatedAt
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.CreatedBy(); !ok {
		v := blog.DefaultCreatedBy
		bc.mutation.SetCreatedBy(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := blog.DefaultUpdatedAt
		bc.mutation.SetUpdatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedBy(); !ok {
		v := blog.DefaultUpdatedBy
		bc.mutation.SetUpdatedBy(v)
	}
	if _, ok := bc.mutation.IsDeleted(); !ok {
		v := blog.DefaultIsDeleted
		bc.mutation.SetIsDeleted(v)
	}
	if _, ok := bc.mutation.DeletedAt(); !ok {
		v := blog.DefaultDeletedAt
		bc.mutation.SetDeletedAt(v)
	}
	if _, ok := bc.mutation.DeletedBy(); !ok {
		v := blog.DefaultDeletedBy
		bc.mutation.SetDeletedBy(v)
	}
	if _, ok := bc.mutation.IsHidden(); !ok {
		v := blog.DefaultIsHidden
		bc.mutation.SetIsHidden(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (bc *BlogCreate) check() error {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Blog.created_at"`)}
	}
	if _, ok := bc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Blog.created_by"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Blog.updated_at"`)}
	}
	if _, ok := bc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "Blog.updated_by"`)}
	}
	if _, ok := bc.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "Blog.is_deleted"`)}
	}
	if _, ok := bc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Blog.deleted_at"`)}
	}
	if _, ok := bc.mutation.DeletedBy(); !ok {
		return &ValidationError{Name: "deleted_by", err: errors.New(`ent: missing required field "Blog.deleted_by"`)}
	}
	if _, ok := bc.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "Blog.account_id"`)}
	}
	if _, ok := bc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Blog.title"`)}
	}
	if _, ok := bc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Blog.description"`)}
	}
	if _, ok := bc.mutation.IsHidden(); !ok {
		return &ValidationError{Name: "is_hidden", err: errors.New(`ent: missing required field "Blog.is_hidden"`)}
	}
	if _, ok := bc.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Blog.tags"`)}
	}
	if _, ok := bc.mutation.Cover(); !ok {
		return &ValidationError{Name: "cover", err: errors.New(`ent: missing required field "Blog.cover"`)}
	}
	if _, ok := bc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Blog.content"`)}
	}
	if v, ok := bc.mutation.Content(); ok {
		if err := blog.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Blog.content": %w`, err)}
		}
	}
	if v, ok := bc.mutation.ID(); ok {
		if err := blog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Blog.id": %w`, err)}
		}
	}
	return nil
}

func (bc *BlogCreate) sqlSave(ctx context.Context) (*Blog, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int32(id)
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BlogCreate) createSpec() (*Blog, *sqlgraph.CreateSpec) {
	var (
		_node = &Blog{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(blog.Table, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt32))
	)
	_spec.OnConflict = bc.conflict
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(blog.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.CreatedBy(); ok {
		_spec.SetField(blog.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(blog.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := bc.mutation.UpdatedBy(); ok {
		_spec.SetField(blog.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := bc.mutation.IsDeleted(); ok {
		_spec.SetField(blog.FieldIsDeleted, field.TypeUint8, value)
		_node.IsDeleted = value
	}
	if value, ok := bc.mutation.DeletedAt(); ok {
		_spec.SetField(blog.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = value
	}
	if value, ok := bc.mutation.DeletedBy(); ok {
		_spec.SetField(blog.FieldDeletedBy, field.TypeString, value)
		_node.DeletedBy = value
	}
	if value, ok := bc.mutation.AccountID(); ok {
		_spec.SetField(blog.FieldAccountID, field.TypeInt32, value)
		_node.AccountID = value
	}
	if value, ok := bc.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := bc.mutation.Description(); ok {
		_spec.SetField(blog.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := bc.mutation.IsHidden(); ok {
		_spec.SetField(blog.FieldIsHidden, field.TypeInt8, value)
		_node.IsHidden = value
	}
	if value, ok := bc.mutation.Tags(); ok {
		_spec.SetField(blog.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := bc.mutation.Cover(); ok {
		_spec.SetField(blog.FieldCover, field.TypeString, value)
		_node.Cover = value
	}
	if value, ok := bc.mutation.Content(); ok {
		_spec.SetField(blog.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Blog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BlogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (bc *BlogCreate) OnConflict(opts ...sql.ConflictOption) *BlogUpsertOne {
	bc.conflict = opts
	return &BlogUpsertOne{
		create: bc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bc *BlogCreate) OnConflictColumns(columns ...string) *BlogUpsertOne {
	bc.conflict = append(bc.conflict, sql.ConflictColumns(columns...))
	return &BlogUpsertOne{
		create: bc,
	}
}

type (
	// BlogUpsertOne is the builder for "upsert"-ing
	//  one Blog node.
	BlogUpsertOne struct {
		create *BlogCreate
	}

	// BlogUpsert is the "OnConflict" setter.
	BlogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BlogUpsert) SetUpdatedAt(v int64) *BlogUpsert {
	u.Set(blog.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BlogUpsert) UpdateUpdatedAt() *BlogUpsert {
	u.SetExcluded(blog.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *BlogUpsert) AddUpdatedAt(v int64) *BlogUpsert {
	u.Add(blog.FieldUpdatedAt, v)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *BlogUpsert) SetUpdatedBy(v string) *BlogUpsert {
	u.Set(blog.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *BlogUpsert) UpdateUpdatedBy() *BlogUpsert {
	u.SetExcluded(blog.FieldUpdatedBy)
	return u
}

// SetIsDeleted sets the "is_deleted" field.
func (u *BlogUpsert) SetIsDeleted(v uint8) *BlogUpsert {
	u.Set(blog.FieldIsDeleted, v)
	return u
}

// UpdateIsDeleted sets the "is_deleted" field to the value that was provided on create.
func (u *BlogUpsert) UpdateIsDeleted() *BlogUpsert {
	u.SetExcluded(blog.FieldIsDeleted)
	return u
}

// AddIsDeleted adds v to the "is_deleted" field.
func (u *BlogUpsert) AddIsDeleted(v uint8) *BlogUpsert {
	u.Add(blog.FieldIsDeleted, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BlogUpsert) SetDeletedAt(v int64) *BlogUpsert {
	u.Set(blog.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BlogUpsert) UpdateDeletedAt() *BlogUpsert {
	u.SetExcluded(blog.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *BlogUpsert) AddDeletedAt(v int64) *BlogUpsert {
	u.Add(blog.FieldDeletedAt, v)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *BlogUpsert) SetDeletedBy(v string) *BlogUpsert {
	u.Set(blog.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *BlogUpsert) UpdateDeletedBy() *BlogUpsert {
	u.SetExcluded(blog.FieldDeletedBy)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *BlogUpsert) SetAccountID(v int32) *BlogUpsert {
	u.Set(blog.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *BlogUpsert) UpdateAccountID() *BlogUpsert {
	u.SetExcluded(blog.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *BlogUpsert) AddAccountID(v int32) *BlogUpsert {
	u.Add(blog.FieldAccountID, v)
	return u
}

// SetTitle sets the "title" field.
func (u *BlogUpsert) SetTitle(v string) *BlogUpsert {
	u.Set(blog.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BlogUpsert) UpdateTitle() *BlogUpsert {
	u.SetExcluded(blog.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *BlogUpsert) SetDescription(v string) *BlogUpsert {
	u.Set(blog.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BlogUpsert) UpdateDescription() *BlogUpsert {
	u.SetExcluded(blog.FieldDescription)
	return u
}

// SetIsHidden sets the "is_hidden" field.
func (u *BlogUpsert) SetIsHidden(v int8) *BlogUpsert {
	u.Set(blog.FieldIsHidden, v)
	return u
}

// UpdateIsHidden sets the "is_hidden" field to the value that was provided on create.
func (u *BlogUpsert) UpdateIsHidden() *BlogUpsert {
	u.SetExcluded(blog.FieldIsHidden)
	return u
}

// AddIsHidden adds v to the "is_hidden" field.
func (u *BlogUpsert) AddIsHidden(v int8) *BlogUpsert {
	u.Add(blog.FieldIsHidden, v)
	return u
}

// SetTags sets the "tags" field.
func (u *BlogUpsert) SetTags(v []string) *BlogUpsert {
	u.Set(blog.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *BlogUpsert) UpdateTags() *BlogUpsert {
	u.SetExcluded(blog.FieldTags)
	return u
}

// SetCover sets the "cover" field.
func (u *BlogUpsert) SetCover(v string) *BlogUpsert {
	u.Set(blog.FieldCover, v)
	return u
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *BlogUpsert) UpdateCover() *BlogUpsert {
	u.SetExcluded(blog.FieldCover)
	return u
}

// SetContent sets the "content" field.
func (u *BlogUpsert) SetContent(v string) *BlogUpsert {
	u.Set(blog.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *BlogUpsert) UpdateContent() *BlogUpsert {
	u.SetExcluded(blog.FieldContent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(blog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BlogUpsertOne) UpdateNewValues() *BlogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(blog.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(blog.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.CreatedBy(); exists {
			s.SetIgnore(blog.FieldCreatedBy)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Blog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BlogUpsertOne) Ignore() *BlogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BlogUpsertOne) DoNothing() *BlogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BlogCreate.OnConflict
// documentation for more info.
func (u *BlogUpsertOne) Update(set func(*BlogUpsert)) *BlogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BlogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BlogUpsertOne) SetUpdatedAt(v int64) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *BlogUpsertOne) AddUpdatedAt(v int64) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateUpdatedAt() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *BlogUpsertOne) SetUpdatedBy(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateUpdatedBy() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetIsDeleted sets the "is_deleted" field.
func (u *BlogUpsertOne) SetIsDeleted(v uint8) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetIsDeleted(v)
	})
}

// AddIsDeleted adds v to the "is_deleted" field.
func (u *BlogUpsertOne) AddIsDeleted(v uint8) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.AddIsDeleted(v)
	})
}

// UpdateIsDeleted sets the "is_deleted" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateIsDeleted() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateIsDeleted()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BlogUpsertOne) SetDeletedAt(v int64) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *BlogUpsertOne) AddDeletedAt(v int64) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateDeletedAt() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *BlogUpsertOne) SetDeletedBy(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateDeletedBy() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateDeletedBy()
	})
}

// SetAccountID sets the "account_id" field.
func (u *BlogUpsertOne) SetAccountID(v int32) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *BlogUpsertOne) AddAccountID(v int32) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateAccountID() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateAccountID()
	})
}

// SetTitle sets the "title" field.
func (u *BlogUpsertOne) SetTitle(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateTitle() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *BlogUpsertOne) SetDescription(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateDescription() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateDescription()
	})
}

// SetIsHidden sets the "is_hidden" field.
func (u *BlogUpsertOne) SetIsHidden(v int8) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetIsHidden(v)
	})
}

// AddIsHidden adds v to the "is_hidden" field.
func (u *BlogUpsertOne) AddIsHidden(v int8) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.AddIsHidden(v)
	})
}

// UpdateIsHidden sets the "is_hidden" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateIsHidden() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateIsHidden()
	})
}

// SetTags sets the "tags" field.
func (u *BlogUpsertOne) SetTags(v []string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateTags() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateTags()
	})
}

// SetCover sets the "cover" field.
func (u *BlogUpsertOne) SetCover(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetCover(v)
	})
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateCover() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateCover()
	})
}

// SetContent sets the "content" field.
func (u *BlogUpsertOne) SetContent(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateContent() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateContent()
	})
}

// Exec executes the query.
func (u *BlogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BlogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BlogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BlogUpsertOne) ID(ctx context.Context) (id int32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BlogUpsertOne) IDX(ctx context.Context) int32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BlogCreateBulk is the builder for creating many Blog entities in bulk.
type BlogCreateBulk struct {
	config
	err      error
	builders []*BlogCreate
	conflict []sql.ConflictOption
}

// Save creates the Blog entities in the database.
func (bcb *BlogCreateBulk) Save(ctx context.Context) ([]*Blog, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Blog, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = bcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BlogCreateBulk) SaveX(ctx context.Context) []*Blog {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BlogCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BlogCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Blog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BlogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (bcb *BlogCreateBulk) OnConflict(opts ...sql.ConflictOption) *BlogUpsertBulk {
	bcb.conflict = opts
	return &BlogUpsertBulk{
		create: bcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bcb *BlogCreateBulk) OnConflictColumns(columns ...string) *BlogUpsertBulk {
	bcb.conflict = append(bcb.conflict, sql.ConflictColumns(columns...))
	return &BlogUpsertBulk{
		create: bcb,
	}
}

// BlogUpsertBulk is the builder for "upsert"-ing
// a bulk of Blog nodes.
type BlogUpsertBulk struct {
	create *BlogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(blog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BlogUpsertBulk) UpdateNewValues() *BlogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(blog.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(blog.FieldCreatedAt)
			}
			if _, exists := b.mutation.CreatedBy(); exists {
				s.SetIgnore(blog.FieldCreatedBy)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BlogUpsertBulk) Ignore() *BlogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BlogUpsertBulk) DoNothing() *BlogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BlogCreateBulk.OnConflict
// documentation for more info.
func (u *BlogUpsertBulk) Update(set func(*BlogUpsert)) *BlogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BlogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BlogUpsertBulk) SetUpdatedAt(v int64) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *BlogUpsertBulk) AddUpdatedAt(v int64) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateUpdatedAt() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *BlogUpsertBulk) SetUpdatedBy(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateUpdatedBy() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetIsDeleted sets the "is_deleted" field.
func (u *BlogUpsertBulk) SetIsDeleted(v uint8) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetIsDeleted(v)
	})
}

// AddIsDeleted adds v to the "is_deleted" field.
func (u *BlogUpsertBulk) AddIsDeleted(v uint8) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.AddIsDeleted(v)
	})
}

// UpdateIsDeleted sets the "is_deleted" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateIsDeleted() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateIsDeleted()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BlogUpsertBulk) SetDeletedAt(v int64) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *BlogUpsertBulk) AddDeletedAt(v int64) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateDeletedAt() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *BlogUpsertBulk) SetDeletedBy(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateDeletedBy() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateDeletedBy()
	})
}

// SetAccountID sets the "account_id" field.
func (u *BlogUpsertBulk) SetAccountID(v int32) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *BlogUpsertBulk) AddAccountID(v int32) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateAccountID() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateAccountID()
	})
}

// SetTitle sets the "title" field.
func (u *BlogUpsertBulk) SetTitle(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateTitle() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *BlogUpsertBulk) SetDescription(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateDescription() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateDescription()
	})
}

// SetIsHidden sets the "is_hidden" field.
func (u *BlogUpsertBulk) SetIsHidden(v int8) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetIsHidden(v)
	})
}

// AddIsHidden adds v to the "is_hidden" field.
func (u *BlogUpsertBulk) AddIsHidden(v int8) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.AddIsHidden(v)
	})
}

// UpdateIsHidden sets the "is_hidden" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateIsHidden() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateIsHidden()
	})
}

// SetTags sets the "tags" field.
func (u *BlogUpsertBulk) SetTags(v []string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateTags() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateTags()
	})
}

// SetCover sets the "cover" field.
func (u *BlogUpsertBulk) SetCover(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetCover(v)
	})
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateCover() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateCover()
	})
}

// SetContent sets the "content" field.
func (u *BlogUpsertBulk) SetContent(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateContent() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateContent()
	})
}

// Exec executes the query.
func (u *BlogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BlogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BlogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BlogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
