// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog/internal/ent/predicate"
	"blog/internal/ent/travelextends"
	"blog/internal/ent/travels"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TravelExtendsQuery is the builder for querying TravelExtends entities.
type TravelExtendsQuery struct {
	config
	ctx         *QueryContext
	order       []travelextends.OrderOption
	inters      []Interceptor
	predicates  []predicate.TravelExtends
	withExtends *TravelsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TravelExtendsQuery builder.
func (teq *TravelExtendsQuery) Where(ps ...predicate.TravelExtends) *TravelExtendsQuery {
	teq.predicates = append(teq.predicates, ps...)
	return teq
}

// Limit the number of records to be returned by this query.
func (teq *TravelExtendsQuery) Limit(limit int) *TravelExtendsQuery {
	teq.ctx.Limit = &limit
	return teq
}

// Offset to start from.
func (teq *TravelExtendsQuery) Offset(offset int) *TravelExtendsQuery {
	teq.ctx.Offset = &offset
	return teq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (teq *TravelExtendsQuery) Unique(unique bool) *TravelExtendsQuery {
	teq.ctx.Unique = &unique
	return teq
}

// Order specifies how the records should be ordered.
func (teq *TravelExtendsQuery) Order(o ...travelextends.OrderOption) *TravelExtendsQuery {
	teq.order = append(teq.order, o...)
	return teq
}

// QueryExtends chains the current query on the "extends" edge.
func (teq *TravelExtendsQuery) QueryExtends() *TravelsQuery {
	query := (&TravelsClient{config: teq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := teq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := teq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(travelextends.Table, travelextends.FieldID, selector),
			sqlgraph.To(travels.Table, travels.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, travelextends.ExtendsTable, travelextends.ExtendsColumn),
		)
		fromU = sqlgraph.SetNeighbors(teq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TravelExtends entity from the query.
// Returns a *NotFoundError when no TravelExtends was found.
func (teq *TravelExtendsQuery) First(ctx context.Context) (*TravelExtends, error) {
	nodes, err := teq.Limit(1).All(setContextOp(ctx, teq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{travelextends.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (teq *TravelExtendsQuery) FirstX(ctx context.Context) *TravelExtends {
	node, err := teq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TravelExtends ID from the query.
// Returns a *NotFoundError when no TravelExtends ID was found.
func (teq *TravelExtendsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(1).IDs(setContextOp(ctx, teq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{travelextends.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (teq *TravelExtendsQuery) FirstIDX(ctx context.Context) int {
	id, err := teq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TravelExtends entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TravelExtends entity is found.
// Returns a *NotFoundError when no TravelExtends entities are found.
func (teq *TravelExtendsQuery) Only(ctx context.Context) (*TravelExtends, error) {
	nodes, err := teq.Limit(2).All(setContextOp(ctx, teq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{travelextends.Label}
	default:
		return nil, &NotSingularError{travelextends.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (teq *TravelExtendsQuery) OnlyX(ctx context.Context) *TravelExtends {
	node, err := teq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TravelExtends ID in the query.
// Returns a *NotSingularError when more than one TravelExtends ID is found.
// Returns a *NotFoundError when no entities are found.
func (teq *TravelExtendsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(2).IDs(setContextOp(ctx, teq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{travelextends.Label}
	default:
		err = &NotSingularError{travelextends.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (teq *TravelExtendsQuery) OnlyIDX(ctx context.Context) int {
	id, err := teq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TravelExtendsSlice.
func (teq *TravelExtendsQuery) All(ctx context.Context) ([]*TravelExtends, error) {
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryAll)
	if err := teq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TravelExtends, *TravelExtendsQuery]()
	return withInterceptors[[]*TravelExtends](ctx, teq, qr, teq.inters)
}

// AllX is like All, but panics if an error occurs.
func (teq *TravelExtendsQuery) AllX(ctx context.Context) []*TravelExtends {
	nodes, err := teq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TravelExtends IDs.
func (teq *TravelExtendsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if teq.ctx.Unique == nil && teq.path != nil {
		teq.Unique(true)
	}
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryIDs)
	if err = teq.Select(travelextends.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (teq *TravelExtendsQuery) IDsX(ctx context.Context) []int {
	ids, err := teq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (teq *TravelExtendsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryCount)
	if err := teq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, teq, querierCount[*TravelExtendsQuery](), teq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (teq *TravelExtendsQuery) CountX(ctx context.Context) int {
	count, err := teq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (teq *TravelExtendsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryExist)
	switch _, err := teq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (teq *TravelExtendsQuery) ExistX(ctx context.Context) bool {
	exist, err := teq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TravelExtendsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (teq *TravelExtendsQuery) Clone() *TravelExtendsQuery {
	if teq == nil {
		return nil
	}
	return &TravelExtendsQuery{
		config:      teq.config,
		ctx:         teq.ctx.Clone(),
		order:       append([]travelextends.OrderOption{}, teq.order...),
		inters:      append([]Interceptor{}, teq.inters...),
		predicates:  append([]predicate.TravelExtends{}, teq.predicates...),
		withExtends: teq.withExtends.Clone(),
		// clone intermediate query.
		sql:  teq.sql.Clone(),
		path: teq.path,
	}
}

// WithExtends tells the query-builder to eager-load the nodes that are connected to
// the "extends" edge. The optional arguments are used to configure the query builder of the edge.
func (teq *TravelExtendsQuery) WithExtends(opts ...func(*TravelsQuery)) *TravelExtendsQuery {
	query := (&TravelsClient{config: teq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	teq.withExtends = query
	return teq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TravelExtends.Query().
//		GroupBy(travelextends.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (teq *TravelExtendsQuery) GroupBy(field string, fields ...string) *TravelExtendsGroupBy {
	teq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TravelExtendsGroupBy{build: teq}
	grbuild.flds = &teq.ctx.Fields
	grbuild.label = travelextends.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//	}
//
//	client.TravelExtends.Query().
//		Select(travelextends.FieldCreatedAt).
//		Scan(ctx, &v)
func (teq *TravelExtendsQuery) Select(fields ...string) *TravelExtendsSelect {
	teq.ctx.Fields = append(teq.ctx.Fields, fields...)
	sbuild := &TravelExtendsSelect{TravelExtendsQuery: teq}
	sbuild.label = travelextends.Label
	sbuild.flds, sbuild.scan = &teq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TravelExtendsSelect configured with the given aggregations.
func (teq *TravelExtendsQuery) Aggregate(fns ...AggregateFunc) *TravelExtendsSelect {
	return teq.Select().Aggregate(fns...)
}

func (teq *TravelExtendsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range teq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, teq); err != nil {
				return err
			}
		}
	}
	for _, f := range teq.ctx.Fields {
		if !travelextends.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if teq.path != nil {
		prev, err := teq.path(ctx)
		if err != nil {
			return err
		}
		teq.sql = prev
	}
	return nil
}

func (teq *TravelExtendsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TravelExtends, error) {
	var (
		nodes       = []*TravelExtends{}
		_spec       = teq.querySpec()
		loadedTypes = [1]bool{
			teq.withExtends != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TravelExtends).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TravelExtends{config: teq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, teq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := teq.withExtends; query != nil {
		if err := teq.loadExtends(ctx, query, nodes, nil,
			func(n *TravelExtends, e *Travels) { n.Edges.Extends = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (teq *TravelExtendsQuery) loadExtends(ctx context.Context, query *TravelsQuery, nodes []*TravelExtends, init func(*TravelExtends), assign func(*TravelExtends, *Travels)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TravelExtends)
	for i := range nodes {
		fk := nodes[i].TravelID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(travels.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "travel_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (teq *TravelExtendsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := teq.querySpec()
	_spec.Node.Columns = teq.ctx.Fields
	if len(teq.ctx.Fields) > 0 {
		_spec.Unique = teq.ctx.Unique != nil && *teq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, teq.driver, _spec)
}

func (teq *TravelExtendsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(travelextends.Table, travelextends.Columns, sqlgraph.NewFieldSpec(travelextends.FieldID, field.TypeInt))
	_spec.From = teq.sql
	if unique := teq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if teq.path != nil {
		_spec.Unique = true
	}
	if fields := teq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, travelextends.FieldID)
		for i := range fields {
			if fields[i] != travelextends.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if teq.withExtends != nil {
			_spec.Node.AddColumnOnce(travelextends.FieldTravelID)
		}
	}
	if ps := teq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := teq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := teq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := teq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (teq *TravelExtendsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(teq.driver.Dialect())
	t1 := builder.Table(travelextends.Table)
	columns := teq.ctx.Fields
	if len(columns) == 0 {
		columns = travelextends.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if teq.sql != nil {
		selector = teq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if teq.ctx.Unique != nil && *teq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range teq.predicates {
		p(selector)
	}
	for _, p := range teq.order {
		p(selector)
	}
	if offset := teq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := teq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TravelExtendsGroupBy is the group-by builder for TravelExtends entities.
type TravelExtendsGroupBy struct {
	selector
	build *TravelExtendsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tegb *TravelExtendsGroupBy) Aggregate(fns ...AggregateFunc) *TravelExtendsGroupBy {
	tegb.fns = append(tegb.fns, fns...)
	return tegb
}

// Scan applies the selector query and scans the result into the given value.
func (tegb *TravelExtendsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tegb.build.ctx, ent.OpQueryGroupBy)
	if err := tegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TravelExtendsQuery, *TravelExtendsGroupBy](ctx, tegb.build, tegb, tegb.build.inters, v)
}

func (tegb *TravelExtendsGroupBy) sqlScan(ctx context.Context, root *TravelExtendsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tegb.fns))
	for _, fn := range tegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tegb.flds)+len(tegb.fns))
		for _, f := range *tegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TravelExtendsSelect is the builder for selecting fields of TravelExtends entities.
type TravelExtendsSelect struct {
	*TravelExtendsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tes *TravelExtendsSelect) Aggregate(fns ...AggregateFunc) *TravelExtendsSelect {
	tes.fns = append(tes.fns, fns...)
	return tes
}

// Scan applies the selector query and scans the result into the given value.
func (tes *TravelExtendsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tes.ctx, ent.OpQuerySelect)
	if err := tes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TravelExtendsQuery, *TravelExtendsSelect](ctx, tes.TravelExtendsQuery, tes, tes.inters, v)
}

func (tes *TravelExtendsSelect) sqlScan(ctx context.Context, root *TravelExtendsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tes.fns))
	for _, fn := range tes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
