// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"blog/internal/ent/account"
	"blog/internal/ent/blog"
	"blog/internal/ent/comment"
	"blog/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinHooks0 := accountMixin[0].Hooks()
	accountMixinHooks1 := accountMixin[1].Hooks()
	account.Hooks[0] = accountMixinHooks0[0]
	account.Hooks[1] = accountMixinHooks0[1]
	account.Hooks[2] = accountMixinHooks1[0]
	accountMixinInters1 := accountMixin[1].Interceptors()
	account.Interceptors[0] = accountMixinInters1[0]
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountMixinFields1 := accountMixin[1].Fields()
	_ = accountMixinFields1
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountMixinFields0[0].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(int64)
	// accountDescCreatedBy is the schema descriptor for created_by field.
	accountDescCreatedBy := accountMixinFields0[1].Descriptor()
	// account.DefaultCreatedBy holds the default value on creation for the created_by field.
	account.DefaultCreatedBy = accountDescCreatedBy.Default.(string)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountMixinFields0[2].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(int64)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() int64)
	// accountDescUpdatedBy is the schema descriptor for updated_by field.
	accountDescUpdatedBy := accountMixinFields0[3].Descriptor()
	// account.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	account.DefaultUpdatedBy = accountDescUpdatedBy.Default.(string)
	// accountDescIsDeleted is the schema descriptor for is_deleted field.
	accountDescIsDeleted := accountMixinFields1[0].Descriptor()
	// account.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	account.DefaultIsDeleted = accountDescIsDeleted.Default.(uint8)
	// accountDescDeletedAt is the schema descriptor for deleted_at field.
	accountDescDeletedAt := accountMixinFields1[1].Descriptor()
	// account.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	account.DefaultDeletedAt = accountDescDeletedAt.Default.(int64)
	// accountDescDeletedBy is the schema descriptor for deleted_by field.
	accountDescDeletedBy := accountMixinFields1[2].Descriptor()
	// account.DefaultDeletedBy holds the default value on creation for the deleted_by field.
	account.DefaultDeletedBy = accountDescDeletedBy.Default.(string)
	// accountDescPassword is the schema descriptor for password field.
	accountDescPassword := accountFields[2].Descriptor()
	// account.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	account.PasswordValidator = accountDescPassword.Validators[0].(func(string) error)
	// accountDescEmail is the schema descriptor for email field.
	accountDescEmail := accountFields[3].Descriptor()
	// account.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	account.EmailValidator = accountDescEmail.Validators[0].(func(string) error)
	// accountDescStatus is the schema descriptor for status field.
	accountDescStatus := accountFields[4].Descriptor()
	// account.DefaultStatus holds the default value on creation for the status field.
	account.DefaultStatus = accountDescStatus.Default.(int8)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.IDValidator is a validator for the "id" field. It is called by the builders before save.
	account.IDValidator = accountDescID.Validators[0].(func(int32) error)
	blogMixin := schema.Blog{}.Mixin()
	blogMixinHooks0 := blogMixin[0].Hooks()
	blogMixinHooks1 := blogMixin[1].Hooks()
	blog.Hooks[0] = blogMixinHooks0[0]
	blog.Hooks[1] = blogMixinHooks0[1]
	blog.Hooks[2] = blogMixinHooks1[0]
	blogMixinInters1 := blogMixin[1].Interceptors()
	blog.Interceptors[0] = blogMixinInters1[0]
	blogMixinFields0 := blogMixin[0].Fields()
	_ = blogMixinFields0
	blogMixinFields1 := blogMixin[1].Fields()
	_ = blogMixinFields1
	blogFields := schema.Blog{}.Fields()
	_ = blogFields
	// blogDescCreatedAt is the schema descriptor for created_at field.
	blogDescCreatedAt := blogMixinFields0[0].Descriptor()
	// blog.DefaultCreatedAt holds the default value on creation for the created_at field.
	blog.DefaultCreatedAt = blogDescCreatedAt.Default.(int64)
	// blogDescCreatedBy is the schema descriptor for created_by field.
	blogDescCreatedBy := blogMixinFields0[1].Descriptor()
	// blog.DefaultCreatedBy holds the default value on creation for the created_by field.
	blog.DefaultCreatedBy = blogDescCreatedBy.Default.(string)
	// blogDescUpdatedAt is the schema descriptor for updated_at field.
	blogDescUpdatedAt := blogMixinFields0[2].Descriptor()
	// blog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blog.DefaultUpdatedAt = blogDescUpdatedAt.Default.(int64)
	// blog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blog.UpdateDefaultUpdatedAt = blogDescUpdatedAt.UpdateDefault.(func() int64)
	// blogDescUpdatedBy is the schema descriptor for updated_by field.
	blogDescUpdatedBy := blogMixinFields0[3].Descriptor()
	// blog.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	blog.DefaultUpdatedBy = blogDescUpdatedBy.Default.(string)
	// blogDescIsDeleted is the schema descriptor for is_deleted field.
	blogDescIsDeleted := blogMixinFields1[0].Descriptor()
	// blog.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	blog.DefaultIsDeleted = blogDescIsDeleted.Default.(uint8)
	// blogDescDeletedAt is the schema descriptor for deleted_at field.
	blogDescDeletedAt := blogMixinFields1[1].Descriptor()
	// blog.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	blog.DefaultDeletedAt = blogDescDeletedAt.Default.(int64)
	// blogDescDeletedBy is the schema descriptor for deleted_by field.
	blogDescDeletedBy := blogMixinFields1[2].Descriptor()
	// blog.DefaultDeletedBy holds the default value on creation for the deleted_by field.
	blog.DefaultDeletedBy = blogDescDeletedBy.Default.(string)
	// blogDescIsHidden is the schema descriptor for is_hidden field.
	blogDescIsHidden := blogFields[4].Descriptor()
	// blog.DefaultIsHidden holds the default value on creation for the is_hidden field.
	blog.DefaultIsHidden = blogDescIsHidden.Default.(int8)
	// blogDescContent is the schema descriptor for content field.
	blogDescContent := blogFields[7].Descriptor()
	// blog.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	blog.ContentValidator = blogDescContent.Validators[0].(func(string) error)
	// blogDescID is the schema descriptor for id field.
	blogDescID := blogFields[0].Descriptor()
	// blog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	blog.IDValidator = blogDescID.Validators[0].(func(int32) error)
	commentMixin := schema.Comment{}.Mixin()
	commentMixinHooks0 := commentMixin[0].Hooks()
	commentMixinHooks1 := commentMixin[1].Hooks()
	comment.Hooks[0] = commentMixinHooks0[0]
	comment.Hooks[1] = commentMixinHooks0[1]
	comment.Hooks[2] = commentMixinHooks1[0]
	commentMixinInters1 := commentMixin[1].Interceptors()
	comment.Interceptors[0] = commentMixinInters1[0]
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentMixinFields1 := commentMixin[1].Fields()
	_ = commentMixinFields1
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentMixinFields0[0].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(int64)
	// commentDescCreatedBy is the schema descriptor for created_by field.
	commentDescCreatedBy := commentMixinFields0[1].Descriptor()
	// comment.DefaultCreatedBy holds the default value on creation for the created_by field.
	comment.DefaultCreatedBy = commentDescCreatedBy.Default.(string)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentMixinFields0[2].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(int64)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() int64)
	// commentDescUpdatedBy is the schema descriptor for updated_by field.
	commentDescUpdatedBy := commentMixinFields0[3].Descriptor()
	// comment.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	comment.DefaultUpdatedBy = commentDescUpdatedBy.Default.(string)
	// commentDescIsDeleted is the schema descriptor for is_deleted field.
	commentDescIsDeleted := commentMixinFields1[0].Descriptor()
	// comment.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	comment.DefaultIsDeleted = commentDescIsDeleted.Default.(uint8)
	// commentDescDeletedAt is the schema descriptor for deleted_at field.
	commentDescDeletedAt := commentMixinFields1[1].Descriptor()
	// comment.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	comment.DefaultDeletedAt = commentDescDeletedAt.Default.(int64)
	// commentDescDeletedBy is the schema descriptor for deleted_by field.
	commentDescDeletedBy := commentMixinFields1[2].Descriptor()
	// comment.DefaultDeletedBy holds the default value on creation for the deleted_by field.
	comment.DefaultDeletedBy = commentDescDeletedBy.Default.(string)
	// commentDescAccountID is the schema descriptor for account_id field.
	commentDescAccountID := commentFields[0].Descriptor()
	// comment.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	comment.AccountIDValidator = commentDescAccountID.Validators[0].(func(int32) error)
	// commentDescKind is the schema descriptor for kind field.
	commentDescKind := commentFields[1].Descriptor()
	// comment.DefaultKind holds the default value on creation for the kind field.
	comment.DefaultKind = commentDescKind.Default.(int8)
	// commentDescKindID is the schema descriptor for kind_id field.
	commentDescKindID := commentFields[2].Descriptor()
	// comment.KindIDValidator is a validator for the "kind_id" field. It is called by the builders before save.
	comment.KindIDValidator = commentDescKindID.Validators[0].(func(int32) error)
	// commentDescTopID is the schema descriptor for top_id field.
	commentDescTopID := commentFields[4].Descriptor()
	// comment.DefaultTopID holds the default value on creation for the top_id field.
	comment.DefaultTopID = commentDescTopID.Default.(int32)
	// commentDescParentID is the schema descriptor for parent_id field.
	commentDescParentID := commentFields[5].Descriptor()
	// comment.DefaultParentID holds the default value on creation for the parent_id field.
	comment.DefaultParentID = commentDescParentID.Default.(int32)
	// commentDescStatus is the schema descriptor for status field.
	commentDescStatus := commentFields[6].Descriptor()
	// comment.DefaultStatus holds the default value on creation for the status field.
	comment.DefaultStatus = commentDescStatus.Default.(int8)
	// commentDescLevel is the schema descriptor for level field.
	commentDescLevel := commentFields[7].Descriptor()
	// comment.DefaultLevel holds the default value on creation for the level field.
	comment.DefaultLevel = commentDescLevel.Default.(int32)
	// commentDescTotal is the schema descriptor for total field.
	commentDescTotal := commentFields[8].Descriptor()
	// comment.DefaultTotal holds the default value on creation for the total field.
	comment.DefaultTotal = commentDescTotal.Default.(int32)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentFields[3].Descriptor()
	// comment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	comment.IDValidator = commentDescID.Validators[0].(func(int32) error)
}

const (
	Version = "v0.14.1"                                         // Version of ent codegen.
	Sum     = "h1:fUERL506Pqr92EPHJqr8EYxbPioflJo6PudkrEA8a/s=" // Sum of ent codegen.
)
