server:
  http:
    addr: 0.0.0.0:1008
    timeout: 1s
  grpc:
    addr: 0.0.0.0:1009
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:pf94514203.gwsee.com@tcp(47.100.14.57:3306)/my_blog?parseTime=True&loc=Local
  redis:
    addr: 47.100.14.57:6379
    pws: OoO0o0ilLi1I1
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  api_key: gwsee
  service_key: blog_account
trace:
  endpoint: http://127.0.0.1:14268/api/traces
etcd:
  Hosts:
    - 47.100.14.57:2379
  Key: app.user.rpc