// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	_ "blog/app/account/internal/biz"
	"blog/app/account/internal/conf"
	"blog/app/account/internal/data"
	"blog/app/account/internal/server"
	"blog/app/account/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	_, cleanup, err := data.NewData(confData, logger) //dataData
	if err != nil {
		return nil, nil, err
	}
	//accountRepo := data.NewGreeterRepo(dataData, logger)
	//accountUsecase := biz.NewGreeterUsecase(accountRepo, logger)
	accountService := service.NewAccountService() //accountUsecase
	grpcServer := server.NewGRPCServer(confServer, accountService, logger)
	httpServer := server.NewHTTPServer(confServer, accountService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
