// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: app/blogs/api/blogs.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBlogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBlogsRequest) Reset() {
	*x = CreateBlogsRequest{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogsRequest) ProtoMessage() {}

func (x *CreateBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogsRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogsRequest) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{0}
}

type CreateBlogsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBlogsReply) Reset() {
	*x = CreateBlogsReply{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogsReply) ProtoMessage() {}

func (x *CreateBlogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogsReply.ProtoReflect.Descriptor instead.
func (*CreateBlogsReply) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{1}
}

type UpdateBlogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBlogsRequest) Reset() {
	*x = UpdateBlogsRequest{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogsRequest) ProtoMessage() {}

func (x *UpdateBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogsRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlogsRequest) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{2}
}

type UpdateBlogsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBlogsReply) Reset() {
	*x = UpdateBlogsReply{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogsReply) ProtoMessage() {}

func (x *UpdateBlogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogsReply.ProtoReflect.Descriptor instead.
func (*UpdateBlogsReply) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{3}
}

type DeleteBlogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBlogsRequest) Reset() {
	*x = DeleteBlogsRequest{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogsRequest) ProtoMessage() {}

func (x *DeleteBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogsRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogsRequest) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{4}
}

type DeleteBlogsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBlogsReply) Reset() {
	*x = DeleteBlogsReply{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogsReply) ProtoMessage() {}

func (x *DeleteBlogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogsReply.ProtoReflect.Descriptor instead.
func (*DeleteBlogsReply) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{5}
}

type GetBlogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBlogsRequest) Reset() {
	*x = GetBlogsRequest{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsRequest) ProtoMessage() {}

func (x *GetBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetBlogsRequest) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{6}
}

type GetBlogsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBlogsReply) Reset() {
	*x = GetBlogsReply{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsReply) ProtoMessage() {}

func (x *GetBlogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsReply.ProtoReflect.Descriptor instead.
func (*GetBlogsReply) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{7}
}

type ListBlogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBlogsRequest) Reset() {
	*x = ListBlogsRequest{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlogsRequest) ProtoMessage() {}

func (x *ListBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlogsRequest.ProtoReflect.Descriptor instead.
func (*ListBlogsRequest) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{8}
}

type ListBlogsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBlogsReply) Reset() {
	*x = ListBlogsReply{}
	mi := &file_app_blogs_api_blogs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlogsReply) ProtoMessage() {}

func (x *ListBlogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_blogs_api_blogs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlogsReply.ProtoReflect.Descriptor instead.
func (*ListBlogsReply) Descriptor() ([]byte, []int) {
	return file_app_blogs_api_blogs_proto_rawDescGZIP(), []int{9}
}

var File_app_blogs_api_blogs_proto protoreflect.FileDescriptor

var file_app_blogs_api_blogs_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x70, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x70,
	0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6c,
	0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c,
	0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42,
	0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x32, 0x97, 0x03, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x51, 0x0a, 0x0b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x21, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x51, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x21,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x51, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67,
	0x73, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67,
	0x73, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4b, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x1f, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x29, 0x0a, 0x0d,
	0x61, 0x70, 0x70, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x50, 0x01, 0x5a,
	0x16, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_blogs_api_blogs_proto_rawDescOnce sync.Once
	file_app_blogs_api_blogs_proto_rawDescData = file_app_blogs_api_blogs_proto_rawDesc
)

func file_app_blogs_api_blogs_proto_rawDescGZIP() []byte {
	file_app_blogs_api_blogs_proto_rawDescOnce.Do(func() {
		file_app_blogs_api_blogs_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_blogs_api_blogs_proto_rawDescData)
	})
	return file_app_blogs_api_blogs_proto_rawDescData
}

var file_app_blogs_api_blogs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_app_blogs_api_blogs_proto_goTypes = []any{
	(*CreateBlogsRequest)(nil), // 0: app.blogs.api.CreateBlogsRequest
	(*CreateBlogsReply)(nil),   // 1: app.blogs.api.CreateBlogsReply
	(*UpdateBlogsRequest)(nil), // 2: app.blogs.api.UpdateBlogsRequest
	(*UpdateBlogsReply)(nil),   // 3: app.blogs.api.UpdateBlogsReply
	(*DeleteBlogsRequest)(nil), // 4: app.blogs.api.DeleteBlogsRequest
	(*DeleteBlogsReply)(nil),   // 5: app.blogs.api.DeleteBlogsReply
	(*GetBlogsRequest)(nil),    // 6: app.blogs.api.GetBlogsRequest
	(*GetBlogsReply)(nil),      // 7: app.blogs.api.GetBlogsReply
	(*ListBlogsRequest)(nil),   // 8: app.blogs.api.ListBlogsRequest
	(*ListBlogsReply)(nil),     // 9: app.blogs.api.ListBlogsReply
}
var file_app_blogs_api_blogs_proto_depIdxs = []int32{
	0, // 0: app.blogs.api.Blogs.CreateBlogs:input_type -> app.blogs.api.CreateBlogsRequest
	2, // 1: app.blogs.api.Blogs.UpdateBlogs:input_type -> app.blogs.api.UpdateBlogsRequest
	4, // 2: app.blogs.api.Blogs.DeleteBlogs:input_type -> app.blogs.api.DeleteBlogsRequest
	6, // 3: app.blogs.api.Blogs.GetBlogs:input_type -> app.blogs.api.GetBlogsRequest
	8, // 4: app.blogs.api.Blogs.ListBlogs:input_type -> app.blogs.api.ListBlogsRequest
	1, // 5: app.blogs.api.Blogs.CreateBlogs:output_type -> app.blogs.api.CreateBlogsReply
	3, // 6: app.blogs.api.Blogs.UpdateBlogs:output_type -> app.blogs.api.UpdateBlogsReply
	5, // 7: app.blogs.api.Blogs.DeleteBlogs:output_type -> app.blogs.api.DeleteBlogsReply
	7, // 8: app.blogs.api.Blogs.GetBlogs:output_type -> app.blogs.api.GetBlogsReply
	9, // 9: app.blogs.api.Blogs.ListBlogs:output_type -> app.blogs.api.ListBlogsReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_blogs_api_blogs_proto_init() }
func file_app_blogs_api_blogs_proto_init() {
	if File_app_blogs_api_blogs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_blogs_api_blogs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_blogs_api_blogs_proto_goTypes,
		DependencyIndexes: file_app_blogs_api_blogs_proto_depIdxs,
		MessageInfos:      file_app_blogs_api_blogs_proto_msgTypes,
	}.Build()
	File_app_blogs_api_blogs_proto = out.File
	file_app_blogs_api_blogs_proto_rawDesc = nil
	file_app_blogs_api_blogs_proto_goTypes = nil
	file_app_blogs_api_blogs_proto_depIdxs = nil
}
