// Code generated by ent, DO NOT EDIT.

package hook

import (
	"blog/internal/ent"
	"context"
	"fmt"
)

// The AccountFunc type is an adapter to allow the use of ordinary
// function as Account mutator.
type AccountFunc func(context.Context, *ent.AccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AccountMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AccountMutation", m)
}

// The BlogsFunc type is an adapter to allow the use of ordinary
// function as Blogs mutator.
type BlogsFunc func(context.Context, *ent.BlogsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BlogsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BlogsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BlogsMutation", m)
}

// The BlogsCommentFunc type is an adapter to allow the use of ordinary
// function as BlogsComment mutator.
type BlogsCommentFunc func(context.Context, *ent.BlogsCommentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BlogsCommentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BlogsCommentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BlogsCommentMutation", m)
}

// The BlogsContentFunc type is an adapter to allow the use of ordinary
// function as BlogsContent mutator.
type BlogsContentFunc func(context.Context, *ent.BlogsContentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BlogsContentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BlogsContentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BlogsContentMutation", m)
}

// The BlogsExtendFunc type is an adapter to allow the use of ordinary
// function as BlogsExtend mutator.
type BlogsExtendFunc func(context.Context, *ent.BlogsExtendMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BlogsExtendFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BlogsExtendMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BlogsExtendMutation", m)
}

// The FilesFunc type is an adapter to allow the use of ordinary
// function as Files mutator.
type FilesFunc func(context.Context, *ent.FilesMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FilesFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FilesMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FilesMutation", m)
}

// The FilesExtendFunc type is an adapter to allow the use of ordinary
// function as FilesExtend mutator.
type FilesExtendFunc func(context.Context, *ent.FilesExtendMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FilesExtendFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FilesExtendMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FilesExtendMutation", m)
}

// The PalacesMemoFunc type is an adapter to allow the use of ordinary
// function as PalacesMemo mutator.
type PalacesMemoFunc func(context.Context, *ent.PalacesMemoMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PalacesMemoFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PalacesMemoMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PalacesMemoMutation", m)
}

// The PalacesMemoryFunc type is an adapter to allow the use of ordinary
// function as PalacesMemory mutator.
type PalacesMemoryFunc func(context.Context, *ent.PalacesMemoryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PalacesMemoryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PalacesMemoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PalacesMemoryMutation", m)
}

// The PalacesTodoFunc type is an adapter to allow the use of ordinary
// function as PalacesTodo mutator.
type PalacesTodoFunc func(context.Context, *ent.PalacesTodoMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PalacesTodoFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PalacesTodoMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PalacesTodoMutation", m)
}

// The PalacesTodoDoneFunc type is an adapter to allow the use of ordinary
// function as PalacesTodoDone mutator.
type PalacesTodoDoneFunc func(context.Context, *ent.PalacesTodoDoneMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PalacesTodoDoneFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PalacesTodoDoneMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PalacesTodoDoneMutation", m)
}

// The TagsFunc type is an adapter to allow the use of ordinary
// function as Tags mutator.
type TagsFunc func(context.Context, *ent.TagsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TagsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TagsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TagsMutation", m)
}

// The TagsRelationFunc type is an adapter to allow the use of ordinary
// function as TagsRelation mutator.
type TagsRelationFunc func(context.Context, *ent.TagsRelationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TagsRelationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TagsRelationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TagsRelationMutation", m)
}

// The TravelExtendsFunc type is an adapter to allow the use of ordinary
// function as TravelExtends mutator.
type TravelExtendsFunc func(context.Context, *ent.TravelExtendsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TravelExtendsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TravelExtendsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TravelExtendsMutation", m)
}

// The TravelsFunc type is an adapter to allow the use of ordinary
// function as Travels mutator.
type TravelsFunc func(context.Context, *ent.TravelsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TravelsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TravelsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TravelsMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
}

// The UserExperienceFunc type is an adapter to allow the use of ordinary
// function as UserExperience mutator.
type UserExperienceFunc func(context.Context, *ent.UserExperienceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserExperienceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserExperienceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserExperienceMutation", m)
}

// The UserFamousQuotesFunc type is an adapter to allow the use of ordinary
// function as UserFamousQuotes mutator.
type UserFamousQuotesFunc func(context.Context, *ent.UserFamousQuotesMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFamousQuotesFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserFamousQuotesMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserFamousQuotesMutation", m)
}

// The UserProjectFunc type is an adapter to allow the use of ordinary
// function as UserProject mutator.
type UserProjectFunc func(context.Context, *ent.UserProjectMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserProjectFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserProjectMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserProjectMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
