// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: api/blogs/v1/blogs.proto

package v1

import (
	global "blog/api/global"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Blogs_CreateBlogs_FullMethodName  = "/api.blogs.v1.Blogs/CreateBlogs"
	Blogs_UpdateBlogs_FullMethodName  = "/api.blogs.v1.Blogs/UpdateBlogs"
	Blogs_DeleteBlogs_FullMethodName  = "/api.blogs.v1.Blogs/DeleteBlogs"
	Blogs_GetBlogs_FullMethodName     = "/api.blogs.v1.Blogs/GetBlogs"
	Blogs_ListBlogs_FullMethodName    = "/api.blogs.v1.Blogs/ListBlogs"
	Blogs_HotBlogs_FullMethodName     = "/api.blogs.v1.Blogs/HotBlogs"
	Blogs_Thumb_FullMethodName        = "/api.blogs.v1.Blogs/Thumb"
	Blogs_Collect_FullMethodName      = "/api.blogs.v1.Blogs/Collect"
	Blogs_ListBlogTags_FullMethodName = "/api.blogs.v1.Blogs/ListBlogTags"
)

// BlogsClient is the client API for Blogs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogsClient interface {
	CreateBlogs(ctx context.Context, in *CreateBlogsRequest, opts ...grpc.CallOption) (*global.Empty, error)
	UpdateBlogs(ctx context.Context, in *UpdateBlogsRequest, opts ...grpc.CallOption) (*global.Empty, error)
	DeleteBlogs(ctx context.Context, in *global.ID, opts ...grpc.CallOption) (*global.Empty, error)
	GetBlogs(ctx context.Context, in *global.ID, opts ...grpc.CallOption) (*GetBlogsReply, error)
	ListBlogs(ctx context.Context, in *ListBlogsRequest, opts ...grpc.CallOption) (*ListBlogsReply, error)
	// 最新 热门文章
	HotBlogs(ctx context.Context, in *global.PageInfo, opts ...grpc.CallOption) (*ListBlogsReply, error)
	// 点赞
	Thumb(ctx context.Context, in *global.Action, opts ...grpc.CallOption) (*global.Empty, error)
	// 收藏
	Collect(ctx context.Context, in *global.Action, opts ...grpc.CallOption) (*global.Empty, error)
	// 标签
	ListBlogTags(ctx context.Context, in *ListBlogsRequest, opts ...grpc.CallOption) (*ListBlogTagsReply, error)
}

type blogsClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogsClient(cc grpc.ClientConnInterface) BlogsClient {
	return &blogsClient{cc}
}

func (c *blogsClient) CreateBlogs(ctx context.Context, in *CreateBlogsRequest, opts ...grpc.CallOption) (*global.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(global.Empty)
	err := c.cc.Invoke(ctx, Blogs_CreateBlogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) UpdateBlogs(ctx context.Context, in *UpdateBlogsRequest, opts ...grpc.CallOption) (*global.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(global.Empty)
	err := c.cc.Invoke(ctx, Blogs_UpdateBlogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) DeleteBlogs(ctx context.Context, in *global.ID, opts ...grpc.CallOption) (*global.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(global.Empty)
	err := c.cc.Invoke(ctx, Blogs_DeleteBlogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) GetBlogs(ctx context.Context, in *global.ID, opts ...grpc.CallOption) (*GetBlogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlogsReply)
	err := c.cc.Invoke(ctx, Blogs_GetBlogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) ListBlogs(ctx context.Context, in *ListBlogsRequest, opts ...grpc.CallOption) (*ListBlogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlogsReply)
	err := c.cc.Invoke(ctx, Blogs_ListBlogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) HotBlogs(ctx context.Context, in *global.PageInfo, opts ...grpc.CallOption) (*ListBlogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlogsReply)
	err := c.cc.Invoke(ctx, Blogs_HotBlogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) Thumb(ctx context.Context, in *global.Action, opts ...grpc.CallOption) (*global.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(global.Empty)
	err := c.cc.Invoke(ctx, Blogs_Thumb_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) Collect(ctx context.Context, in *global.Action, opts ...grpc.CallOption) (*global.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(global.Empty)
	err := c.cc.Invoke(ctx, Blogs_Collect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) ListBlogTags(ctx context.Context, in *ListBlogsRequest, opts ...grpc.CallOption) (*ListBlogTagsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlogTagsReply)
	err := c.cc.Invoke(ctx, Blogs_ListBlogTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogsServer is the server API for Blogs service.
// All implementations must embed UnimplementedBlogsServer
// for forward compatibility.
type BlogsServer interface {
	CreateBlogs(context.Context, *CreateBlogsRequest) (*global.Empty, error)
	UpdateBlogs(context.Context, *UpdateBlogsRequest) (*global.Empty, error)
	DeleteBlogs(context.Context, *global.ID) (*global.Empty, error)
	GetBlogs(context.Context, *global.ID) (*GetBlogsReply, error)
	ListBlogs(context.Context, *ListBlogsRequest) (*ListBlogsReply, error)
	// 最新 热门文章
	HotBlogs(context.Context, *global.PageInfo) (*ListBlogsReply, error)
	// 点赞
	Thumb(context.Context, *global.Action) (*global.Empty, error)
	// 收藏
	Collect(context.Context, *global.Action) (*global.Empty, error)
	// 标签
	ListBlogTags(context.Context, *ListBlogsRequest) (*ListBlogTagsReply, error)
	mustEmbedUnimplementedBlogsServer()
}

// UnimplementedBlogsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlogsServer struct{}

func (UnimplementedBlogsServer) CreateBlogs(context.Context, *CreateBlogsRequest) (*global.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBlogs not implemented")
}
func (UnimplementedBlogsServer) UpdateBlogs(context.Context, *UpdateBlogsRequest) (*global.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBlogs not implemented")
}
func (UnimplementedBlogsServer) DeleteBlogs(context.Context, *global.ID) (*global.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBlogs not implemented")
}
func (UnimplementedBlogsServer) GetBlogs(context.Context, *global.ID) (*GetBlogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlogs not implemented")
}
func (UnimplementedBlogsServer) ListBlogs(context.Context, *ListBlogsRequest) (*ListBlogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlogs not implemented")
}
func (UnimplementedBlogsServer) HotBlogs(context.Context, *global.PageInfo) (*ListBlogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HotBlogs not implemented")
}
func (UnimplementedBlogsServer) Thumb(context.Context, *global.Action) (*global.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thumb not implemented")
}
func (UnimplementedBlogsServer) Collect(context.Context, *global.Action) (*global.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedBlogsServer) ListBlogTags(context.Context, *ListBlogsRequest) (*ListBlogTagsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlogTags not implemented")
}
func (UnimplementedBlogsServer) mustEmbedUnimplementedBlogsServer() {}
func (UnimplementedBlogsServer) testEmbeddedByValue()               {}

// UnsafeBlogsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogsServer will
// result in compilation errors.
type UnsafeBlogsServer interface {
	mustEmbedUnimplementedBlogsServer()
}

func RegisterBlogsServer(s grpc.ServiceRegistrar, srv BlogsServer) {
	// If the following call pancis, it indicates UnimplementedBlogsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Blogs_ServiceDesc, srv)
}

func _Blogs_CreateBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).CreateBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blogs_CreateBlogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).CreateBlogs(ctx, req.(*CreateBlogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_UpdateBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).UpdateBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blogs_UpdateBlogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).UpdateBlogs(ctx, req.(*UpdateBlogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_DeleteBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(global.ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).DeleteBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blogs_DeleteBlogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).DeleteBlogs(ctx, req.(*global.ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_GetBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(global.ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).GetBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blogs_GetBlogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).GetBlogs(ctx, req.(*global.ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_ListBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).ListBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blogs_ListBlogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).ListBlogs(ctx, req.(*ListBlogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_HotBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(global.PageInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).HotBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blogs_HotBlogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).HotBlogs(ctx, req.(*global.PageInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_Thumb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(global.Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).Thumb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blogs_Thumb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).Thumb(ctx, req.(*global.Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(global.Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blogs_Collect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).Collect(ctx, req.(*global.Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_ListBlogTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).ListBlogTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blogs_ListBlogTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).ListBlogTags(ctx, req.(*ListBlogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blogs_ServiceDesc is the grpc.ServiceDesc for Blogs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blogs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.blogs.v1.Blogs",
	HandlerType: (*BlogsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBlogs",
			Handler:    _Blogs_CreateBlogs_Handler,
		},
		{
			MethodName: "UpdateBlogs",
			Handler:    _Blogs_UpdateBlogs_Handler,
		},
		{
			MethodName: "DeleteBlogs",
			Handler:    _Blogs_DeleteBlogs_Handler,
		},
		{
			MethodName: "GetBlogs",
			Handler:    _Blogs_GetBlogs_Handler,
		},
		{
			MethodName: "ListBlogs",
			Handler:    _Blogs_ListBlogs_Handler,
		},
		{
			MethodName: "HotBlogs",
			Handler:    _Blogs_HotBlogs_Handler,
		},
		{
			MethodName: "Thumb",
			Handler:    _Blogs_Thumb_Handler,
		},
		{
			MethodName: "Collect",
			Handler:    _Blogs_Collect_Handler,
		},
		{
			MethodName: "ListBlogTags",
			Handler:    _Blogs_ListBlogTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/blogs/v1/blogs.proto",
}
